### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Net

### ISSUE THREAD

**Issue by WuZhuoran** [jmisilo/clip-gpt-captioning#82]
Following the README to run predict over one image. Get this error and full traceback here:

```
Downloading (…)rocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 316/316 [00:00<00:00, 455kB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 905/905 [00:00<00:00, 2.46MB/s]
Downloading (…)olve/main/vocab.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 961k/961k [00:00<00:00, 5.32MB/s]
Downloading (…)olve/main/merges.txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 4.15MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2.22M/2.22M [00:00<00:00, 6.59MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1.20MB/s]
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 4.52k/4.52k [00:00<00:00, 7.80MB/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Downloading pytorch_model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.71G/1.71G [00:39<00:00, 43.7MB/s]
Downloading (…)olve/main/vocab.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 5.57MB/s]
Downloading (…)olve/main/merges.txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 38.5MB/s]
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 718/718 [00:00<00:00, 2.03MB/s]
Downloading model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.52G/1.52G [00:35<00:00, 43.4MB/s]
Downloading (…)neration_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:00<00:00, 521kB/s]
Traceback (most recent call last):
  File "/Users/oliver/Documents/git/clip-gpt-captioning/src/predict.py", line 104, in <module>
    model.load_state_dict(checkpoint)
  File "/Users/oliver/Documents/git/clip-gpt-captioning/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Net:
	Unexpected key(s) in state_dict: "ie.model.embeddings.position_ids", "td.model.transformer.h.0.attn.bias", "td.model.transformer.h.0.attn.masked_bias", "td.model.transformer.h.1.attn.bias", "td.model.transformer.h.1.attn.masked_bias", "td.model.transformer.h.2.attn.bias", "td.model.transformer.h.2.attn.masked_bias", "td.model.transformer.h.3.attn.bias", "td.model.transformer.h.3.attn.masked_bias", "td.model.transformer.h.4.attn.bias", "td.model.transformer.h.4.attn.masked_bias", "td.model.transformer.h.5.attn.bias", "td.model.transformer.h.5.attn.masked_bias", "td.model.transformer.h.6.attn.bias", "td.model.transformer.h.6.attn.masked_bias", "td.model.transformer.h.7.attn.bias", "td.model.transformer.h.7.attn.masked_bias", "td.model.transformer.h.8.attn.bias", "td.model.transformer.h.8.attn.masked_bias", "td.model.transformer.h.9.attn.bias", "td.model.transformer.h.9.attn.masked_bias", "td.model.transformer.h.10.attn.bias", "td.model.transformer.h.10.attn.masked_bias", "td.model.transformer.h.11.attn.bias", "td.model.transformer.h.11.attn.masked_bias", "td.model.transformer.h.12.attn.bias", "td.model.transformer.h.12.attn.masked_bias", "td.model.transformer.h.13.attn.bias", "td.model.transformer.h.13.attn.masked_bias", "td.model.transformer.h.14.attn.bias", "td.model.transformer.h.14.attn.masked_bias", "td.model.transformer.h.15.attn.bias", "td.model.transformer.h.15.attn.masked_bias", "td.model.transformer.h.16.attn.bias", "td.model.transformer.h.16.attn.masked_bias", "td.model.transformer.h.17.attn.bias", "td.model.transformer.h.17.attn.masked_bias", "td.model.transformer.h.18.attn.bias", "td.model.transformer.h.18.attn.masked_bias", "td.model.transformer.h.19.attn.bias", "td.model.transformer.h.19.attn.masked_bias", "td.model.transformer.h.20.attn.bias", "td.model.transformer.h.20.attn.masked_bias", "td.model.transformer.h.21.attn.bias", "td.model.transformer.h.21.attn.masked_bias", "td.model.transformer.h.22.attn.bias", "td.model.transformer.h.22.attn.masked_bias", "td.model.transformer.h.23.attn.bias", "td.model.transformer.h.23.attn.masked_bias".
```

System Environment:

```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.4 (main, Jun 15 2023, 07:55:38) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
```

**Comment by San-Di** [comment]
Hello~
I had the exact same problem when I installed `transformers` the latest version `pip install transformers` (with no version defined). The problem is solved when I changed it back to `pip install transformers==4.27.4
` as user recommended in his `requirements.txt` file. 

 I hope it helps

**Comment by WuZhuoran** [comment]
> Hello~ I had the exact same problem when I installed `transformers` the latest version `pip install transformers` (with no version defined). The problem is solved when I changed it back to `pip install transformers==4.27.4 ` as the author recommended in his `requirements.txt` file.
> 
> I hope it helps.

Hi SanDi, thank you for your reply. I resolaved this issue by disabling the `torch` install and install again in my environment. Then rerun the `pip install transformers` and it works fine even with latest version. I think this error happened because my environment did not even install this before. 

but still thanks for this version update.
